services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=carlos_diego
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors_bucket
    volumes:
      - ./almacenamiento:/var/lib/influxdb2
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend/app
      dockerfile: ../Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

  cliente_dragino:
    build:
      context: ./cliente_dragino/
    container_name: cliente_dragino
    depends_on:
      - backend
    networks:
      - app_network

  cliente_milesight:
    build:
      context: ./cliente_milesight/
    container_name: cliente_milesight
    depends_on:
      - backend
    networks:
      - app_network

  cliente_rak:
    build:
      context: ./cliente_rak
    container_name: cliente_rak
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
